# Generated by Django 4.1.2 on 2023-11-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP_address',
            fields=[
                ('ip_address', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('vlan_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
