# Generated by Django 4.1.2 on 2023-11-16 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VPNapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBelongsToVLAN',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VPNapp.vlan')),
            ],
        ),
        migrations.CreateModel(
            name='UserRestrictedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VPNapp.ip_address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ip_address')},
            },
        ),
    ]
