# Generated by Django 4.1.2 on 2023-11-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VPNapp', '0002_userbelongstovlan_userrestrictedip'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLANRestrictedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VPNapp.ip_address')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VPNapp.vlan')),
            ],
            options={
                'unique_together': {('vlan', 'ip_address')},
            },
        ),
    ]
